version: "3"

volumes:
  node_modules:
services:
  my-app-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3002:3000"
      - "24678:24678"
    volumes:
      - .:/src
      - node_modules:/src/node_modules