name: agirlpic-nuxt3 CI-CD
run-name: agirlpic.com build and running CI-CD with Nuxt 3, docker-compose
on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.VPS_SSH_HOST }}
                username: ${{ secrets.VPS_SSH_USERNAME }}
                passphrase: ${{ secrets.SSH_PASSPHRASE }}
                key: ${{ secrets.VPS_SSH_SECRET }}
                port: ${{ secrets.VPS_SSH_PORT }}
                script: |
                    cd ${{ secrets.PROJECT_PATH }}
                    docker compose down
                    git pull
                    docker compose build
                    docker compose up
                    docker image prune -a -f
                    echo "CI completed"